// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HelloReply
 */
export type HelloReply = {
    /**
     * Message
     */
    message: string;
    /**
     * Docs Url
     */
    docs_url: string;
};

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hello';
};

export type GetHelloResponses = {
    /**
     * Successful Response
     */
    200: HelloReply;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];
